apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ucb
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "backend"
        static_configs:
          - targets: ["backend:8080"]
