auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache

limits_config:
  allow_structured_metadata: false

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

query_scheduler: {}

memberlist:
  join_members: []

compactor:
  working_directory: /loki/compactor
