server:
  http_listen_port: 9080

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "backend-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "backend"
          __path__: /var/log/backend.log
